### ISSUE TITLE
Feature (internal): Deploy scripts for development and deployment

### ISSUE THREAD

**Issue by L235** [L235/formAssistant#11]
when commits get merged to `dev` or `main` branches:
- in the case of `dev`, deploy to "User:L235/formFiller.js" on Wikipedia, but change CONFIG_PAGE to "User:L235/form-config.json" and comment out the `            return; // Silently exit – nothing to do here` if not on base page
- in the case of `main`, deploy to "MediaWiki:Form-assistant.js" on Wikipedia, no changes

from https://github.com/GeneralNotability/spihelper for inspiration:

.github/workflows/dev-deploy.yml:
```
name: Deploy to Wikipedia (dev branch)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install deploy dependencies
        run: |
          pip install mwparserfromhell>=0.5.0 pywikibot

      # Runs a set of commands using the runners shell
      - name: Run deploy script
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
        run: |
          echo "('GeneralNotability', BotPassword('${BOT_NAME}', '${BOT_PASS}'))" > user-password.py
          chmod 600 user-password.py
          python3 deploy.py --file spihelper.js --target User:GeneralNotability/spihelper-dev.js --summary "Deploying revision [$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/${GITHUB_SHA} ${GITHUB_SHA}]"
```

deploy.py:
```
import argparse
import pywikibot


def main(target, file_to_deploy, summary):
    site = pywikibot.Site('en', 'wikipedia')
    page = pywikibot.Page(site, target)
    with open(file_to_deploy, 'r') as source_file:
        page.text = source_file.read()

    page.save(summary)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--target', help='Target page')
    parser.add_argument('--file', help='File to deploy')
    parser.add_argument('--summary', help='Edit summary')
    args = parser.parse_args()
    main(args.target, args.file, args.summary)
```
